# ROS 2 Galactic Geochelone development environment based on Ubuntu 20.04.
#
# Roberto Masocco <robmasocco@gmail.com>
# Alessandro Tenaglia <alessandro.tenaglia42@gmail.com>
#
# January 25, 2022

# Start from a basic Ubuntu 20.04 image
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install basic utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
  apt-utils \
  curl \
  iproute2 \
  openssh-client \
  python3-pip \
  software-properties-common \
  sudo && \
  add-apt-repository universe && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*/apt/lists/*

# Install language and locales
RUN apt-get update && apt-get install -y \
  locales && \
  locale-gen en_US.UTF-8 && \
  update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*/apt/lists/*
ENV LANG en_US.UTF-8

# Install ROS 2 Galactic Geochelone base and testing packages
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
  apt-get update && apt-get install -y --no-install-recommends \
  gnupg2 \
  libasio-dev \
  libtinyxml2-dev \
  lsb-release \
  python3-argcomplete \
  python3-colcon-argcomplete \
  python3-colcon-common-extensions \
  python3-rosdep \
  ros-galactic-ament-lint \
  ros-galactic-camera-calibration \
  ros-galactic-camera-calibration-parsers \
  ros-galactic-camera-info-manager \
  ros-galactic-eigen3-cmake-module \
  ros-galactic-image-common \
  ros-galactic-image-pipeline \
  ros-galactic-image-transport \
  ros-galactic-image-transport-plugins \
  ros-galactic-launch-testing \
  ros-galactic-launch-testing-ament-cmake \
  ros-galactic-launch-testing-ros \
  ros-galactic-rmw-fastrtps-cpp \
  ros-galactic-ros-base && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*/apt/lists/*
RUN yes | pip3 install -U \
  empy \
  opencv-contrib-python \
  opencv-python \
  pyros-genmsg \
  setuptools \
  testresources

# Install remaining ROS 2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
  ros-galactic-desktop \
  ros-galactic-gazebo-ros-pkgs && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*/apt/lists/*

# Configure ROS MiddleWare implementation to use
ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp

# Install development tools
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  cmake \
  gdb \
  git \
  htop \
  less \
  nano \
  pylint3 \
  python3-vcstool \
  python3-autopep8 \
  uncrustify \
  valgrind \
  vim \
  wget && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*/apt/lists/*

# Install Zsh
RUN apt-get update && apt-get install -y --no-install-recommends \
  chroma \
  zsh \
  zsh-doc && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Cleanup
RUN apt-get autoclean && \
  apt-get autoremove && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*/apt/lists/*

# Set environment variables
ENV ROS_DISTRO=galactic
ENV AMENT_PREFIX_PATH=/opt/ros/galactic
ENV COLCON_PREFIX_PATH=/opt/ros/galactic
ENV LD_LIBRARY_PATH=/opt/ros/galactic/lib
ENV PATH=/opt/ros/galactic/bin:$PATH
ENV PYTHONPATH=/opt/ros/galactic/lib/python3.8/site-packages
ENV ROS_PYTHON_VERSION=3
ENV ROS_VERSION=2

ENV DEBIAN_FRONTEND=dialog

# Add image information
LABEL author.name="Roberto Masocco"
LABEL author.email="robmasocco@gmail.com"
LABEL organization="Intelligent Systems Lab"
LABEL description="ROS 2 Galactic Geochelone development container"

# Start shell in container
CMD ["bash"]
